### PR TITLE
track qcom common

### PR DESCRIPTION
**Pull request by vishal-android-freak**
-This fixes error finding dtbToolCM

### CODE REVIEW

**Comment by championswimmer** [comment]
The best way to take this should be via the cm gerrit

**Comment by vishal-android-freak** [comment]
gotcha

**Comment by DooMLoRD** [comment]
@vishal-android-freak pulled & merged the update from CM repo

**Comment by vishal-android-freak** [comment]
Cool :D Thanks @DooMLoRD

**Pull request closed without merging**
